### ISSUE TITLE
Unhide the notch

### ISSUE THREAD

**Issue by tommynordli** [ignaciojuarez/ByeNotch#1]
Do you know how I can get the notch back again? 😅

**Comment by tommynordli** [comment]
Realised now that you could simply change the wallpaper to show the notch again

**Comment by ignaciojuarez** [comment]
Hello Tommy,Thank you for reaching out! Which Macbook do you have? You should be able to simply click the menu bar icon again and click Hi Notch, that’s what it should say when you are hiding the notch (after clicking bye Notch).Let me know if it doesn’t work, i’ll show you another way ;)Ignacio JuarezOn Jan 11, 2024, at 1:31 PM, Tommy Nordli ***@***.***> wrote:﻿
Do you know how I can get the notch back again? 😅
